inherit_from: .rubocop_todo.yml

# For more cops go here https://raw.githubusercontent.com/rubocop-hq/rubocop/master/config/default.yml
# To install rubocop as git hook run "git config core.hooksPath .githooks"

require:
  - rubocop-chr
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails
  - rubocop-graphql

AllCops:
  RubyInterpreters:
    - ruby
  Include:
    - "**/*.rb"
    - "**/*.arb"
    - "**/*.axlsx"
    - "**/*.builder"
    - "**/*.fcgi"
    - "**/*.gemfile"
    - "**/*.gemspec"
    - "**/*.god"
    - "**/*.jb"
    - "**/*.jbuilder"
    - "**/*.mspec"
    - "**/*.opal"
    - "**/*.pluginspec"
    - "**/*.podspec"
    - "**/*.rabl"
    - "**/*.rake"
    - "**/*.rbuild"
    - "**/*.rbw"
    - "**/*.rbx"
    - "**/*.ru"
    - "**/*.ruby"
    - "**/*.spec"
    - "**/*.thor"
    - "**/*.watchr"
    - "**/.irbrc"
    - "**/.pryrc"
    - "**/buildfile"
    - "**/Appraisals"
    - "**/Berksfile"
    - "**/Brewfile"
    - "**/Buildfile"
    - "**/Capfile"
    - "**/Cheffile"
    - "**/Dangerfile"
    - "**/Deliverfile"
    - "**/Fastfile"
    - "**/*Fastfile"
    - "**/Gemfile"
    - "**/Guardfile"
    - "**/Jarfile"
    - "**/Mavenfile"
    - "**/Podfile"
    - "**/Puppetfile"
    - "**/Rakefile"
    - "**/Snapfile"
    - "**/Thorfile"
    - "**/Vagabondfile"
    - "**/Vagrantfile"
  Exclude:
    - "node_modules/**/*"
    - "**/node_modules/**/*"
    - "vendor/**/*"
    - ".git/**/*"
    - "tmp/**/*"
    - "db/schema.rb"
    - "lib/rubocop-chr/**/*"

  DefaultFormatter: progress
  DisplayCopNames: true
  DisplayStyleGuide: false
  StyleGuideBaseURL: https://rubystyle.guide
  ExtraDetails: false
  StyleGuideCopsOnly: false
  UseCache: true
  MaxFilesInCache: 20000
  CacheRootDirectory: tmp/rubocop
  AllowSymlinksInCacheRootDirectory: false
  TargetRubyVersion: 3.3.7
  NewCops: enable
  # Change DisabledByDefault to false to enable all cops locally
  # Please don't commit the changed line
  DisabledByDefault: true

Bundler/OrderedGems:
  Enabled: true

RSpec:
  Enabled: true

RSpec/ExpectChange:
  EnforcedStyle: block


RSpec/Focus:
  Enabled: true

# Use `foo {}` not `foo{}`.
Layout/SpaceBeforeBlockBraces:
  Enabled: true

# Use `foo { bar }` not `foo {bar}`.
Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyleForEmptyBraces: space
# Use `{ a: 1 }` not `{a:1}`.
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

# Check quotes usage according to lint rule below.
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

# Detect hard tabs, no hard tabs.
Layout/IndentationStyle:
  Enabled: true

# Blank lines should not have any spaces.
Layout/TrailingEmptyLines:
  Enabled: true

# No trailing whitespace.
Layout/TrailingWhitespace:
  Enabled: true

Layout/AccessModifierIndentation:
  Enabled: true
  EnforcedStyle: outdent

Layout/CaseIndentation:
  Enabled: true

Layout/ElseAlignment:
  Enabled: true

Layout/EndAlignment:
  Enabled: true
  AutoCorrect: true
  EnforcedStyleAlignWith: variable

Layout/AssignmentIndentation:
  Enabled: true
  IndentationWidth: 2

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/IndentationConsistency:
  Enabled: true

Layout/InitialIndentation:
  Enabled: true

Layout/LeadingEmptyLines:
  Enabled: true

Layout/MultilineAssignmentLayout:
  Enabled: true

Layout/MultilineBlockLayout:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/RescueEnsureAlignment:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAfterMethodName:
  Enabled: true

Layout/SpaceAfterNot:
  Enabled: true

Layout/SpaceAfterSemicolon:
  Enabled: true

Layout/SpaceAroundBlockParameters:
  Enabled: true

Layout/SpaceAroundKeyword:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceBeforeComma:
  Enabled: true

Layout/SpaceBeforeComment:
  Enabled: true

Layout/SpaceBeforeSemicolon:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space

Layout/SpaceInsideStringInterpolation:
  Enabled: true
  EnforcedStyle: no_space

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/BlockAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_block

Layout/BlockEndNewline:
  Enabled: true

Layout/ClosingParenthesisIndentation:
  Enabled: true

Layout/ConditionPosition:
  Enabled: true

Layout/DefEndAlignment:
  Enabled: true
  AutoCorrect: true

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: trailing

Layout/EmptyComment:
  Enabled: true

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true
  Width: 2
  AllowedPatterns:
    ['^\s*module', '^\s*class', '^\s*private', '^\s*protected', '^\s*public']

Layout/LeadingCommentSpace:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true
  EnforcedStyle: space

Layout/SpaceInsideParens:
  Enabled: true
  EnforcedStyle: no_space

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: true

Layout/SpaceInsideRangeLiteral:
  Enabled: true

Layout/SpaceInsideReferenceBrackets:
  Enabled: true

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: key
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/LineLength:
  Enabled: false
  Exclude:
    - "spec/**/*"
    - "lib/**/*"
    - "db/**/*"

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Rails/EnvironmentComparison:
  Enabled: true

Rails/FindEach:
  Enabled: true

Rails/Presence:
  Enabled: true

Rails/TimeZone:
  Enabled: true

Rails7/CustomToSWithArgument:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - "spec/**/*"

Style/HashSyntax:
  Enabled: false

Style/DefWithParentheses:
  Enabled: true

Style/MethodCallWithoutArgsParentheses:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/NilComparison:
  Enabled: true

Style/Proc:
  Enabled: true

Style/RedundantBegin:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Style/UnlessElse:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/AndOr:
  Enabled: true
  EnforcedStyle: always

Style/Not:
  Enabled: true

Performance/BindCall:
  Enabled: true

Performance/Caller:
  Enabled: true

Performance/Casecmp:
  Enabled: true

Performance/CompareWithBlock:
  Enabled: true

Performance/Count:
  Enabled: true

Performance/DeletePrefix:
  Enabled: true

Performance/DeleteSuffix:
  Enabled: true

Performance/DoubleStartEndWith:
  Enabled: true

Performance/EndWith:
  Enabled: true

Performance/FixedSize:
  Enabled: true

Performance/FlatMap:
  Enabled: true

Performance/InefficientHashSearch:
  Enabled: true

Performance/RangeInclude:
  Enabled: true

Performance/RedundantBlockCall:
  Enabled: true

Performance/RedundantMatch:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

Performance/ReverseEach:
  Enabled: true

Performance/Size:
  Enabled: true

Performance/StartWith:
  Enabled: true

Performance/StringReplacement:
  Enabled: true

Performance/TimesMap:
  Enabled: true

Performance/UnfreezeString:
  Enabled: true

Performance/UriDefaultParser:
  Enabled: true

Lint/Debugger:
  Enabled: true

Lint/DuplicateHashKey:
  Enabled: true

Lint/Syntax:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: true

Style/RescueStandardError:
  Enabled: true
  EnforcedStyle: implicit

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/MultilineArrayBraceLayout:
  Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true

Layout/MultilineOperationIndentation:
  Enabled: true

Layout/ArgumentAlignment:
  Enabled: true

# Temporary not defined so disabled

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

GraphQL:
  Enabled: true

GraphQL/ObjectDescription:
  Enabled: false

GraphQL/FieldDescription:
  Enabled: false

GraphQL/ArgumentDescription:
  Enabled: false

GraphQL/ExtractInputType:
  Enabled: false

GraphQL/ExtractType:
  Enabled: false

GraphQL/UnusedArgument:
  Enabled: false

Flag/FeatureFlagName:
  Enabled: true

Rails5/StringConditional:
  Enabled: true

Rails6/NoUpdateAttributes:
  Enabled: true

Naming/MethodName:
  Enabled: true

MultipleMemoizedHelpers:
  Enabled: false

# Prepare for Ruby 3.0
Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Style/EndlessMethod:
  Enabled: true

Style/HashExcept:
  Enabled: true

Style/KeywordParametersOrder:
  Enabled: true

Lint/RedundantSplatExpansion:
  Enabled: true

Lint/SendWithMixinArgument:
  Enabled: true

Lint/NumberedParameterAssignment:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/UselessTimes:
  Enabled: true

Lint/DeprecatedConstants:
  Enabled: true

Lint/DuplicateRequire:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true

Lint/FloatOutOfRange:
  Enabled: true

Lint/MultipleComparison:
  Enabled: true

Lint/UriRegexp:
  Enabled: true
# Enable once we are on Ruby 3.0
# Lint/EndlessMethodDefinition:
#   Enabled: true
# Lint/UriEscapeUnescape:
#   Enabled: true
